#!/usr/bin/python
import pss
import os

home=os.environ["HOME"]

fileObj = open(home + "/.cdargs", "r")

lines=[]
for line in fileObj:
    # each line contains a mark and a target, we store a tuple of mark and
    # target in the list.
    lines.append(line.strip().split(" "))

# find the maximum length of the mark to format the strings.
maxMarkLen=len(
    # max returns a tuple containing mark as [0] element.
    max(
        lines, 
        # find max based on the len of first element in the tuple
        key = lambda x: len(x[0])
    )[0]
)

# create a new list containing each element as a formatted string of format
# [mark] : target
inLines = []
for mark, target in lines:
    inLines.append("[" + mark.ljust(maxMarkLen) + "] " + target)

pss.MyApp({
    "file"  : home + "/.cdargsresult",
    "lines" : inLines,
})
